version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker container
          command: docker build -t ci-test-docker-microservice-template ./ --no-cache
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /docker-cache
            docker save -o /docker-cache/ci-test-docker-microservice-template.tar ci-test-docker-microservice-template
      - save_cache:
          key: docker_cache_ci
          paths:
            - docker-cache/ci-test-docker-microservice-template.tar
  publish-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: docker_cache_ci
      - run:
          name: ls -la
          command: ls -la /
      - run:
          name: ls -la
          command: ls -la /root/project/
      - run:
          name: Load Image from Cache
          command: docker load -i docker-cache/ci-test-docker-microservice-template.tar
      - run:
          name: Tag the docker image
          command: docker tag ci-test-docker-microservice-template:latest 367608115228.dkr.ecr.eu-central-1.amazonaws.com/ci-test-docker-microservice-template:latest
      - run:
          name: Push the docker image
          command: docker push 367608115228.dkr.ecr.eu-central-1.amazonaws.com/ci-test-docker-microservice-template:latest
workflows:
  version: 2
  build-publish-image:
    jobs:
      - build
      - publish-image:
          requires:
            - build
          filters:
            branches:
              only: master
